Testing for DEC OSF's -threads option before looking for libpthreads

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,7 +1,7 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(Tickertape.c)
 AM_INIT_AUTOMAKE(xtickertape, 1.5.3)
-AM_CONFIG_HEADER(config.h)
+dnl AM_CONFIG_HEADER(config.h)
 
 
 dnl Special elvin-related setup.
@@ -44,11 +44,24 @@ dnl Checks for libraries.
 dnl =====================
 
 dnl The elvin C library requires pthreads
-AC_CHECK_LIB(pthread, pthread_create, LIBS="-lpthread $LIBS" ; ok=yes , ok=no)
+dnl See if the compiler accepts the -threads flag (likely DEC OSF)
+AC_MSG_CHECKING(whether $CC accepts -threads)
+ac_save_LIBS="$LIBS"
+LIBS="$LIBS -threads"
+AC_TRY_LINK(, "/* Test */\nint main() { pthread_create(); return 0; }", ok=yes, ok=no)
+AC_MSG_RESULT($ok)
+
+dnl If we didn't succeed, then revert LIBS back to what it used to be
+dnl and see if we can find the pthreads library
 if test "$ok" = "no" ; then
-	echo "ERROR: \`libpthreads' is missing on your system.  xtickertape"
-	echo "       cannot be compiled without it.  Sorry."
-	exit 1
+	echo "bar"
+	LIBS="$ac_save_LIBS"
+	AC_CHECK_LIB(pthread, pthread_create, LIBS="-lpthread $LIBS" ; ok=yes , ok=no)
+	if test "$ok" = "no" ; then
+		echo "ERROR: \`libpthreads' is missing on your system.  xtickertape"
+		echo "       cannot be compiled without it.  Sorry."
+		exit 1
+	fi
 fi
 
 dnl Check to see if we need -lnsl -lsocket to use sockets
