Using elvin-config to generate the list of libraries

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -17,6 +17,10 @@ AC_SEARCH_LIBS(gethostbyname, nsl)
 # See if we need -lcrypt for the crypt library
 AC_SEARCH_LIBS(crypt, crypt)
 
+# See if we need -lm for fmod()
+# FIX THIS: this should go in elvin-config somehow
+AC_SEARCH_LIBS(fmod, m)
+
 # Figure out where X11 lives.
 AC_PATH_X
 if test "$no_x" = yes ; then
@@ -44,26 +48,25 @@ AC_ARG_WITH(elvin, [  --with-elvin=DIR       specify the elvin4 installation dir
 
 # Check for silliness
 if test "$with_elvin" = no ; then
-    AC_MSG_ERROR("xcoffeebiff cannot be compiled without elvin4")
+    AC_MSG_ERROR([xtickertape cannot be compiled without elvin4])
     exit 1
 fi
 
-# See if a directory was provided
-if test "$with_elvin" != yes ; then
-    CPPFLAGS="-I$withval/include $CPPFLAGS"
-    LDFLAGS="-L$withval/lib $LDFLAGS"
+# Locate the elvin-config script
+AC_PATH_PROG(ELVIN_CONFIG, elvin-config, not found, $withval/bin:$PATH)
+if test "$ELVIN_CONFIG" = "not found" ; then
+	echo "WARNING: \`elvin-config' is missing on your system.  It"
+	echo "         is normally installed as part of the elvin4 libraries,"
+	echo "         which is available from http://elvin.dstc.edu.au/"
+	exit 1
 fi
 
-# Check for the various libraries
-AC_CHECK_LIB(vin4c, elvin_client_init,
-    LIBS="-lvin4c -lvin4 $LIBS -lm",
-    AC_MSG_ERROR("unable to locate the elvin4 libraries"); exit 1,
-    -lvin4c -lvin4 -lm)
+# Update our flags to pick up the elvin includes and libraries
+CFLAGS="$CFLAGS `$ELVIN_CONFIG --cflags vin4Xt`"
+LIBS="`$ELVIN_CONFIG --libs vin4Xt` $LIBS"
 
-AC_CHECK_LIB(vin4Xt, elvin_xt_init,
-    LIBS="-lvin4Xt $LIBS",
-    AC_MSG_ERROR("unable to locate the elvin4 Xt main loop library"); exit 1
-    -lvin4Xt)
+# Make sure we link with the elvin libraries
+AC_SEARCH_LIBS(elvin_xt_init, c)
 
 dnl Checks for header files.
 AC_HEADER_STDC
